type Language = 'english' | 'spanish';

export const isLanguage = (str: unknown): str is Language => str === 'spanish' || str === 'english'

export const words: Record<Language, string[]> = {
  english: [
    'the sun shines in the blue sky',
    'the moon illuminates the dark night',
    'the breeze blows gently on the beach',
    'the cars circulate on the road',
    'the grass is green in the meadow',
    'the clock marks the hours',
    'the house is white',
    'the noise of the city is constant',
    'the guitar sounds melodious',
    'the sea extends to the horizon',
    'hard work yields good results',
    'life is an exciting journey',
    'the fire warms the environment',
    'love unites people',
    'the shadow is projected on the wall',
    'knowledge opens doors',
    'the earth revolves around the sun',
    'colors fill the canvas',
    'the world is a diverse place',
    'patience is a virtue',
    'fishes swim in the sea',
    'teamwork bears fruit',
    'nature is amazing',
    'the sun sets on the horizon',
    'the night is dark and silent',
    'the sunset paints the sky with colors',
    'sports promote an active lifestyle',
    'science advances in giant steps',
    'astronauts travel to outer space',
    'silence reigns in the library',
    'wild animals inhabit the jungle',
    'seafood is delicious and healthy',
    'volunteers help those in need',
    'the stars shine in the firmament',
    'airplanes fly through the skies',
    'teamwork strengthens bonds',
    'waves break on the coast',
    'fair trade promotes equity',
    'horses gallop in the field',
    'chocolate is a culinary pleasure',
    'monuments reflect history',
    'whispers fill the classroom',
    'flowers beautify the gardens',
    'trains travel to different destinations',
    'constellations decorate the night sky',
    'seas hide underwater treasures',
    'digital commerce grows exponentially',
    'butterflies flutter in the field',
    'chess is a game of strategy',
    'migratory birds cross continents',
    'architects design impressive buildings',
    'waterfalls fall with force on the rock',
    'art inspires and moves',
    'bees work hard to produce honey',
    'winter brings the magic of christmas',
    'motorcycles speed along the roads',
    'ice cream is a refreshing sweet in summer',
    'the seasons change the landscape',
    'the forest is home to various animals',
    'chameleons change color to camouflage',
    'the universe is vast and unexplored',
    'seashells contain secrets of the sea',
    'elephants have a great memory',
    'karate is a traditional martial art',
    'kites fly high in the sky',
    'continuous learning enriches the mind',
    'cruises sail on international waters',
    'dolphins jump out of the water',
    'karaoke entertains singing enthusiasts',
    'surfing is practiced on the sea waves',
    'the ice cream seller sells ice creams on the beach',
    'monks meditate in the monastery',
    'kites are flying toys',
    'the farmer cultivates his fields',
    'the telescope observes the stars in the sky',
    'tamers train lions in the circus',
    'the fox is clever and elusive',
    'mimes entertain on the streets',
  ],
  spanish: [
    'el sol brilla en el cielo azul',
    'la luna ilumina la noche oscura',
    'la brisa sopla suavemente en la playa',
    'los coches circulan por la carretera',
    'la hierba es verde en el prado',
    'el reloj marca las horas',
    'la casa es de color blanco',
    'el ruido de la ciudad es constante',
    'la guitarra suena melodiosa',
    'el mar se extiende hasta el horizonte',
    'el trabajo duro da buenos resultados',
    'la vida es un viaje emocionante',
    'el fuego calienta el ambiente',
    'el amor une a las personas',
    'la sombra se proyecta en la pared',
    'el conocimiento abre puertas',
    'la tierra gira alrededor del sol',
    'los colores llenan el lienzo',
    'el mundo es un lugar diverso',
    'la paciencia es una virtud',
    'los peces nadan en el mar',
    'el trabajo en equipo da frutos',
    'la naturaleza es asombrosa',
    'el sol se oculta en el horizonte',
    'la noche es oscura y silenciosa',
    'el ocaso pinta el cielo de colores',
    'los deportes promueven un estilo de vida activo',
    'la ciencia avanza a pasos agigantados',
    'los astronautas viajan al espacio exterior',
    'el silencio reina en la biblioteca',
    'los animales salvajes habitan en la selva',
    'el marisco es delicioso y saludable',
    'los voluntarios ayudan a los necesitados',
    'las estrellas brillan en el firmamento',
    'los aviones vuelan por los cielos',
    'el trabajo en equipo fortalece los lazos',
    'las olas rompen en la costa',
    'el comercio justo promueve la equidad',
    'los caballos galopan en el campo',
    'el chocolate es un placer culinario',
    'los monumentos reflejan la historia',
    'los murmullos llenan la sala de clases',
    'las flores embellecen los jardines',
    'los trenes viajan a distintos destinos',
    'las constelaciones decoran el cielo nocturno',
    'los mares esconden tesoros submarinos',
    'el comercio digital crece exponencialmente',
    'las mariposas revolotean en el campo',
    'el ajedrez es un juego de estrategia',
    'las aves migratorias cruzan continentes',
    'las cascadas caen con fuerza en la roca',
    'el arte inspira y emociona',
    'las abejas trabajan duro para producir miel',
    'el invierno trae consigo la magia de la navidad',
    'las motos recorren las carreteras a toda velocidad',
    'el helado es un dulce refrescante en verano',
    'el bosque es hogar de diversos animales',
    'los camaleones cambian de color para camuflarse',
    'el universo es vasto e inexplorado',
    'las caracolas contienen secretos del mar',
    'los elefantes tienen una gran memoria',
    'el karate es un arte marcial tradicional',
    'las cometas vuelan alto en el cielo',
    'el aprendizaje continuo enriquece la mente',
    'los cruceros navegan por aguas internacionales',
    'los delfines saltan fuera del agua',
    'el karaoke divierte a los aficionados del canto',
    'el surf se practica en las olas del mar',
    'el heladero vende helados en la playa',
    'los monjes meditan en el monasterio',
    'las cometas son juguetes voladores',
    'el granjero cultiva sus campos',
    'el telescopio observa los astros en el cielo',
    'los domadores entrenan a los leones en el circo',
    'el zorro es astuto y escurridizo',
    'los mimos entretienen en las calles',
  ]

}
